/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Controlador.Interfaces.ICInstDeportiva;
import Datatypes.DtInstitucionDeportiva;

import javax.swing.*;

/**
 *
 * @author marti
 */
public class InstitucionDeportiva extends javax.swing.JFrame {
    
    ICInstDeportiva controlador;
    
    public InstitucionDeportiva(ICInstDeportiva controlador) {
        this.controlador = controlador;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInstitucionDeportiva = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        JListInstituciones = new javax.swing.JList<>();
        BtnModificarInstitucion = new javax.swing.JButton();
        BtnAgregarInstitucion = new javax.swing.JButton();
        PanelInfoInstitucion = new javax.swing.JPanel();
        jLabelNombreInstitucion = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabelURLInstitucion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelDescripcionInstitucion = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextDescripcionInstitucion = new javax.swing.JTextArea();
        LabelNombreInstitucion = new javax.swing.JLabel();
        LabelURLInstitucion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lista de instituciones");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JListInstituciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JListInstitucionesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(JListInstituciones);

        BtnModificarInstitucion.setText("Modificar");
        BtnModificarInstitucion.setEnabled(false);
        BtnModificarInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarInstitucionActionPerformed(evt);
            }
        });

        BtnAgregarInstitucion.setText("Agregar");
        BtnAgregarInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarInstitucionActionPerformed(evt);
            }
        });

        PanelInfoInstitucion.setEnabled(false);

        jLabelNombreInstitucion.setText("Nombre");

        jLabelURLInstitucion.setText("URL");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Información de la institucion");

        jLabelDescripcionInstitucion.setText("Descripcion");

        TextDescripcionInstitucion.setColumns(20);
        TextDescripcionInstitucion.setRows(5);
        TextDescripcionInstitucion.setEnabled(false);
        jScrollPane6.setViewportView(TextDescripcionInstitucion);

        LabelNombreInstitucion.setText("-");

        LabelURLInstitucion.setText("-");

        javax.swing.GroupLayout PanelInfoInstitucionLayout = new javax.swing.GroupLayout(PanelInfoInstitucion);
        PanelInfoInstitucion.setLayout(PanelInfoInstitucionLayout);
        PanelInfoInstitucionLayout.setHorizontalGroup(
            PanelInfoInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoInstitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInfoInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(jSeparator15)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelInfoInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabelNombreInstitucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelNombreInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabelURLInstitucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelURLInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoInstitucionLayout.createSequentialGroup()
                        .addComponent(jLabelDescripcionInstitucion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        PanelInfoInstitucionLayout.setVerticalGroup(
            PanelInfoInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoInstitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(PanelInfoInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreInstitucion)
                    .addComponent(LabelNombreInstitucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelURLInstitucion)
                    .addComponent(LabelURLInstitucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescripcionInstitucion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelInstitucionDeportivaLayout = new javax.swing.GroupLayout(PanelInstitucionDeportiva);
        PanelInstitucionDeportiva.setLayout(PanelInstitucionDeportivaLayout);
        PanelInstitucionDeportivaLayout.setHorizontalGroup(
            PanelInstitucionDeportivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInstitucionDeportivaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInstitucionDeportivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInstitucionDeportivaLayout.createSequentialGroup()
                        .addComponent(BtnModificarInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAgregarInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelInfoInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        PanelInstitucionDeportivaLayout.setVerticalGroup(
            PanelInstitucionDeportivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInstitucionDeportivaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInstitucionDeportivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelInfoInstitucion, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addGroup(PanelInstitucionDeportivaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelInstitucionDeportivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAgregarInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnModificarInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelInstitucionDeportiva, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelInstitucionDeportiva, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JListInstitucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListInstitucionesMouseClicked
        //Nombre
        LabelNombreInstitucion.setText(JListInstituciones.getSelectedValue().getNombre());
        //URL
        LabelURLInstitucion.setText(JListInstituciones.getSelectedValue().getUrl());
        //Descripcion
        TextDescripcionInstitucion.setText(JListInstituciones.getSelectedValue().getDesc());

        //Habilitar Modificacion de institucion
        BtnModificarInstitucion.setEnabled(true);
    }//GEN-LAST:event_JListInstitucionesMouseClicked

    private void BtnModificarInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarInstitucionActionPerformed
        ModificarInstitucion modificarInstitucion = new ModificarInstitucion(JListInstituciones.getSelectedValue());
        modificarInstitucion.setVisible(true);
        modificarInstitucion.setLocationRelativeTo(null);
        modificarInstitucion.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_BtnModificarInstitucionActionPerformed

    private void BtnAgregarInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarInstitucionActionPerformed
        AgregarInstitucion agregarInstitucionFrame = new AgregarInstitucion();
        agregarInstitucionFrame.setVisible(true);
        agregarInstitucionFrame.setLocationRelativeTo(null);
        agregarInstitucionFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_BtnAgregarInstitucionActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        cargarListaInstitucionesDeportivas();
    }//GEN-LAST:event_formWindowGainedFocus

    
    public void cargarListaInstitucionesDeportivas(){
        DefaultListModel<DtInstitucionDeportiva> listModel = new DefaultListModel<DtInstitucionDeportiva>();
        listModel.addAll(controlador.getInstituciones());
        JListInstituciones.setModel(listModel);
    }
    
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarInstitucion;
    private javax.swing.JButton BtnModificarInstitucion;
    private javax.swing.JList<DtInstitucionDeportiva> JListInstituciones;
    private javax.swing.JLabel LabelNombreInstitucion;
    private javax.swing.JLabel LabelURLInstitucion;
    private javax.swing.JPanel PanelInfoInstitucion;
    private javax.swing.JPanel PanelInstitucionDeportiva;
    private javax.swing.JTextArea TextDescripcionInstitucion;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDescripcionInstitucion;
    private javax.swing.JLabel jLabelNombreInstitucion;
    private javax.swing.JLabel jLabelURLInstitucion;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator21;
    // End of variables declaration//GEN-END:variables
}
