/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Controlador.Interfaces.*;
import Datatypes.DtActividadDeportiva;
import Datatypes.DtClase;
import Datatypes.DtInstitucionDeportiva;
import Datatypes.DtSocio;
import Excepciones.RegistroExistenteException;

import javax.swing.*;

public class Registro extends javax.swing.JFrame {

    ICInstDeportiva controladorInstitucion;
    ICActDeportiva controladorActividad;
    ICClase controladorClase;
    ICUsuario controladorUsuario;
    ICRegistro controladorRegistro;

    public Registro(ICInstDeportiva controladorInstitucion, ICActDeportiva controladorActividad, ICClase controladorClase, ICUsuario controladorUsuario, ICRegistro controladorRegistro) {
        this.controladorInstitucion = controladorInstitucion;
        this.controladorActividad = controladorActividad;
        this.controladorClase = controladorClase;
        this.controladorUsuario = controladorUsuario;
        this.controladorRegistro = controladorRegistro;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegistro = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboInstitucion = new javax.swing.JComboBox<>();
        comboActividad = new javax.swing.JComboBox<>();
        btnRegistrarSocio = new javax.swing.JButton();
        jSeparator48 = new javax.swing.JSeparator();
        jSeparator49 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaSocio = new javax.swing.JList<>();
        PanelInfoSocio = new javax.swing.JPanel();
        jLabelNickName6 = new javax.swing.JLabel();
        jSeparator44 = new javax.swing.JSeparator();
        jSeparator45 = new javax.swing.JSeparator();
        jLabelNombre6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator46 = new javax.swing.JSeparator();
        jLabelEmail6 = new javax.swing.JLabel();
        jSeparator47 = new javax.swing.JSeparator();
        jLabelFechaNac6 = new javax.swing.JLabel();
        labelNicknameSocio = new javax.swing.JLabel();
        labelNombreSocio = new javax.swing.JLabel();
        labelEmailSocio = new javax.swing.JLabel();
        labelFechaNacSocio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        listaClase = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        PanelInfoClase = new javax.swing.JPanel();
        jLabelNickName3 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jLabelNombre3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        jLabelEmail3 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jLabelFechaNac3 = new javax.swing.JLabel();
        jLabelDescripcion3 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        labelNombreClase = new javax.swing.JLabel();
        labelFechaClase = new javax.swing.JLabel();
        labelHoraInicioClase = new javax.swing.JLabel();
        labelURLClase = new javax.swing.JLabel();
        labelFechaRegistroClase = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelInfoClase.setVisible(false);
        PanelInfoSocio.setVisible(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Seleccionar institución");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Seleccionar actividad");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboInstitucion.setEnabled(false);
        comboInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInstitucionActionPerformed(evt);
            }
        });

        comboActividad.setEnabled(false);
        comboActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActividadActionPerformed(evt);
            }
        });

        btnRegistrarSocio.setText("Registar");
        btnRegistrarSocio.setEnabled(false);
        btnRegistrarSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSocioActionPerformed(evt);
            }
        });

        jPanel2.setPreferredSize(new java.awt.Dimension(562, 289));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Seleccionar socio");

        listaSocio.setEnabled(false);
        listaSocio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaSocioMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(listaSocio);

        PanelInfoSocio.setEnabled(false);
        PanelInfoSocio.setFocusable(false);
        PanelInfoSocio.setPreferredSize(new java.awt.Dimension(268, 267));

        jLabelNickName6.setText("Nickname");

        jLabelNombre6.setText("Nombre");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Información del socio");

        jLabelEmail6.setText("Email");

        jLabelFechaNac6.setText("Fecha de nacimiento");

        labelNicknameSocio.setText("-");

        labelNombreSocio.setText("-");

        labelEmailSocio.setText("-");

        labelFechaNacSocio.setText("-");

        javax.swing.GroupLayout PanelInfoSocioLayout = new javax.swing.GroupLayout(PanelInfoSocio);
        PanelInfoSocio.setLayout(PanelInfoSocioLayout);
        PanelInfoSocioLayout.setHorizontalGroup(
            PanelInfoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoSocioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInfoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator44)
                    .addComponent(jSeparator45, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator46, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator47, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelInfoSocioLayout.createSequentialGroup()
                        .addComponent(jLabelNickName6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNicknameSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoSocioLayout.createSequentialGroup()
                        .addComponent(jLabelNombre6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNombreSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoSocioLayout.createSequentialGroup()
                        .addComponent(jLabelEmail6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEmailSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoSocioLayout.createSequentialGroup()
                        .addComponent(jLabelFechaNac6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFechaNacSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        PanelInfoSocioLayout.setVerticalGroup(
            PanelInfoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoSocioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(PanelInfoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNickName6)
                    .addComponent(labelNicknameSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator44, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre6)
                    .addComponent(labelNombreSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator45, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail6)
                    .addComponent(labelEmailSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator46, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoSocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaNac6)
                    .addComponent(labelFechaNacSocio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator47, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(PanelInfoSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelInfoSocio, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane9)))
                .addContainerGap())
        );

        listaClase.setEnabled(false);
        listaClase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaClaseMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(listaClase);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Seleccionar clase");

        PanelInfoClase.setEnabled(false);
        PanelInfoClase.setFocusable(false);

        jLabelNickName3.setText("Nombre");

        jLabelNombre3.setText("Fecha");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Información de clase");

        jLabelEmail3.setText("Hora de inicio");

        jLabelFechaNac3.setText("URL");

        jLabelDescripcion3.setText("Fecha de registro");

        labelNombreClase.setText("-");

        labelFechaClase.setText("-");

        labelHoraInicioClase.setText("-");

        labelURLClase.setText("-");

        labelFechaRegistroClase.setText("-");

        javax.swing.GroupLayout PanelInfoClaseLayout = new javax.swing.GroupLayout(PanelInfoClase);
        PanelInfoClase.setLayout(PanelInfoClaseLayout);
        PanelInfoClaseLayout.setHorizontalGroup(
            PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoClaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator25)
                    .addComponent(jSeparator26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator29, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelInfoClaseLayout.createSequentialGroup()
                        .addComponent(jLabelNickName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoClaseLayout.createSequentialGroup()
                        .addComponent(jLabelNombre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFechaClase, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoClaseLayout.createSequentialGroup()
                        .addComponent(jLabelEmail3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHoraInicioClase, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoClaseLayout.createSequentialGroup()
                        .addComponent(jLabelFechaNac3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelURLClase, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelInfoClaseLayout.createSequentialGroup()
                        .addComponent(jLabelDescripcion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFechaRegistroClase, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelInfoClaseLayout.setVerticalGroup(
            PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoClaseLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNickName3)
                    .addComponent(labelNombreClase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre3)
                    .addComponent(labelFechaClase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator26, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail3)
                    .addComponent(labelHoraInicioClase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaNac3)
                    .addComponent(labelURLClase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelInfoClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcion3)
                    .addComponent(labelFechaRegistroClase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PanelInfoClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanelInfoClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelRegistroLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(PanelRegistroLayout.createSequentialGroup()
                                .addComponent(comboInstitucion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14)))
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistroLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator49)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addComponent(jSeparator48, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(btnRegistrarSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator49, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator48, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaClaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaClaseMouseClicked
        labelNombreClase.setText(listaClase.getSelectedValue().getNombre());
        labelFechaClase.setText(listaClase.getSelectedValue().getFecha().toString());
        labelHoraInicioClase.setText(listaClase.getSelectedValue().getHoraInicio().toString());
        labelURLClase.setText(listaClase.getSelectedValue().getUrl());
        labelFechaRegistroClase.setText(listaClase.getSelectedValue().getFechaReg().toString());

        PanelInfoClase.setVisible(true);

        cargarListaSocios();
        listaSocio.setVisible(true);
    }//GEN-LAST:event_listaClaseMouseClicked

    private void listaSocioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaSocioMouseClicked
        labelNicknameSocio.setText(listaSocio.getSelectedValue().getNickname());
        labelNombreSocio.setText(listaSocio.getSelectedValue().getNombre());
        labelEmailSocio.setText(listaSocio.getSelectedValue().getMail());
        labelFechaNacSocio.setText(listaSocio.getSelectedValue().getFechaNac().toString());

        PanelInfoSocio.setVisible(true);

        btnRegistrarSocio.setEnabled(true);
    }//GEN-LAST:event_listaSocioMouseClicked

    private void btnRegistrarSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSocioActionPerformed
        DtClase clase = listaClase.getSelectedValue();
        DtSocio socio = listaSocio.getSelectedValue();

        Logica.Registro registro = new Logica.Registro(clase.getNombre(), socio.getNickname());

        try {
            controladorRegistro.altaRegistro(registro);
            controladorClase.registroSocio(clase, registro);
            controladorUsuario.registroClase(socio, registro);

            JOptionPane.showMessageDialog(this, "Socio " + socio.getNickname() + " registrado a clase " + clase.getNombre() + "!", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (RegistroExistenteException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al registrar.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarSocioActionPerformed

    private void comboActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActividadActionPerformed
        cargarListaClases();
        listaClase.setVisible(true);
    }//GEN-LAST:event_comboActividadActionPerformed

    private void comboInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInstitucionActionPerformed
        cargarComboActividadesDeportivas();
        listaClase.setVisible(false);
        PanelInfoClase.setVisible(false);
        listaSocio.setVisible(false);
        PanelInfoSocio.setVisible(false);
        btnRegistrarSocio.setEnabled(false);
    }//GEN-LAST:event_comboInstitucionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarComboInstitucionesDeportivas();
    }//GEN-LAST:event_formWindowOpened

    public void cargarComboInstitucionesDeportivas(){
        if(controladorInstitucion.getInstituciones().isEmpty()) return;

        DefaultComboBoxModel<DtInstitucionDeportiva> comboModel = new DefaultComboBoxModel<DtInstitucionDeportiva>();
        comboModel.addAll(controladorInstitucion.getInstituciones());
        comboInstitucion.setModel(comboModel);
        comboInstitucion.setEnabled(true);
    }

    public void cargarComboActividadesDeportivas(){
        if(controladorActividad.getActividades().isEmpty()) return;
        DtInstitucionDeportiva institucionDeportiva = (DtInstitucionDeportiva) comboInstitucion.getSelectedItem();

        DefaultComboBoxModel<DtActividadDeportiva> comboModel = new DefaultComboBoxModel<DtActividadDeportiva>();
        comboModel.addAll(controladorInstitucion.getActividadesDeInstitucion(institucionDeportiva.getNombre()));
        comboActividad.setModel(comboModel);
        comboActividad.setEnabled(true);

        PanelInfoClase.setEnabled(true);
    }
    
    public void cargarListaClases(){
        DtActividadDeportiva actividadSeleccionada = (DtActividadDeportiva) comboActividad.getSelectedItem();

        if(controladorActividad.getClases(actividadSeleccionada).isEmpty()) return;
        
        DefaultListModel<DtClase> listModel = new DefaultListModel<DtClase>();
        listModel.addAll(controladorActividad.getClases(actividadSeleccionada));
        listaClase.setModel(listModel);
        listaClase.setEnabled(true);
    }
    
    public void cargarListaSocios(){
        if(controladorUsuario.getSocios().isEmpty()) return;
        
        DefaultListModel<DtSocio> listModel = new DefaultListModel<DtSocio>();
        listModel.addAll(controladorUsuario.getSocios());
        listaSocio.setModel(listModel);
        listaSocio.setEnabled(true);
    }
    
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInfoClase;
    private javax.swing.JPanel PanelInfoSocio;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JButton btnRegistrarSocio;
    private javax.swing.JComboBox<DtActividadDeportiva> comboActividad;
    private javax.swing.JComboBox<DtInstitucionDeportiva> comboInstitucion;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabelDescripcion3;
    private javax.swing.JLabel jLabelEmail3;
    private javax.swing.JLabel jLabelEmail6;
    private javax.swing.JLabel jLabelFechaNac3;
    private javax.swing.JLabel jLabelFechaNac6;
    private javax.swing.JLabel jLabelNickName3;
    private javax.swing.JLabel jLabelNickName6;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelNombre6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator49;
    private javax.swing.JLabel labelEmailSocio;
    private javax.swing.JLabel labelFechaClase;
    private javax.swing.JLabel labelFechaNacSocio;
    private javax.swing.JLabel labelFechaRegistroClase;
    private javax.swing.JLabel labelHoraInicioClase;
    private javax.swing.JLabel labelNicknameSocio;
    private javax.swing.JLabel labelNombreClase;
    private javax.swing.JLabel labelNombreSocio;
    private javax.swing.JLabel labelURLClase;
    private javax.swing.JList<DtClase> listaClase;
    private javax.swing.JList<DtSocio> listaSocio;
    // End of variables declaration//GEN-END:variables
}
